#!/bin/bash

# A simple script to take screenshoot using scrot
# Then add date to the file name
# Then open the result instantly using Viewnior

slop=$(slop -f "%g") || exit 1
read -r G < <(echo $slop)
import -window root -crop $G ~/Pictures/Screenshot_$(date +%Y%m%d%H%M%S.png)

notify-send "Screenshot have been taken."